name: Microsoft Teams Release Notification

on:
  release:
    types:
      - released

jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 
    - name: Notify of release
      uses: aliencube/microsoft-teams-actions@v0.8.0
      if: ${{ github.event.release.prerelease == 'false' }}
      with:
        webhook_uri: ${{ secrets.TEAMS_RELEASES_WEBHOOK }}
        title: JavaScript.SDK ${{ github.event.release.tag_name }} was just released!
        summary: Have a look at the release notes ${{ github.event.release.url }}
        text: ${{ github.event.release.body }}
    - name: Notify of prerelease
      uses: aliencube/microsoft-teams-actions@v0.8.0
      if: ${{ github.event.release.prerelease == 'true' }}
      with:
        webhook_uri: ${{ secrets.TEAMS_PRERELEASES_WEBHOOK }}
        title: JavaScript.SDK ${{ github.event.release.tag_name }} was just released!
        summary: Have a look at the release notes ${{ github.event.release.url }}
        text: ${{ github.event.release.body }}
    
